{
 "title": "Keepalived Exporter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(keepalived_up, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Keepalived Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Keepalived Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "keepalived_up", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Health Check Script Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "expr": "keepalived_script_status", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Health Check Script State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "targets": [
    { "expr": "keepalived_script_state", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "VRRP State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "keepalived_vrrp_state",
     "legendFormat": "{{ instance }} ({{ ip_address }})"
    }
   ]
  },
  {
   "title": "Release Master",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_release_master_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Become Master",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_become_master_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Advertisements Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_advertisements_received_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Advertisements Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_advertisements_sent_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Priority Zero Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_priority_zero_received_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Priority Zero Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_priority_zero_sent_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Packet Length Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_packet_length_errors_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Advertisement Interval Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_advertisements_interval_errors_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "TTL Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_ip_ttl_errors_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Address List Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_address_list_errors_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Invalid Type Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_invalid_type_received_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Gratuitous ARP Delay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_gratuitous_arp_delay_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Auth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Authentication Invalid",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_authentication_invalid_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Authentication Mismatch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_authentication_mismatch_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Authentication Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_authentication_failure_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}