name: Continuous Integration

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [1.14, 1.15]

    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: make dep

    - name: Build
      run: make build
  
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [1.14, 1.15]

    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: make dep

    - name: Test
      run: make test


  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        go: [1.15]

    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Check lints
      run: sudo make lint

  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag pavelmikhalchuk/keepalived_exporter:$(git rev-parse --short "$GITHUB_SHA")
      - name: Push Docker image
        run: docker push pavelmikhalchuk/keepalived_exporter:$(git rev-parse --short "$GITHUB_SHA")
